name: Pull Request
on: pull_request
jobs:
  lint:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    name: Test with Jest/RTL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test:ci